### ISSUE TITLE
The project isn't working in Android Studio 1.2 RC 2

### ISSUE THREAD

**Issue by fernandocamargoti** [android10/Android-CleanArchitecture#18]
I tried to open the project with Android Studio (File > Open... > root build.gradle). No erros appears, expect that if I try to open any source file, the editor shows compilation errors about not finding the classes imported. It seems that Android Studio isn't understanding the dependencies of the modules.

**Comment by fernandocamargoti** [comment]
Sorry, after closing and opening the project, it worked.
